project:
  type: book
execute: 
  freeze: auto
book:
  title: "{{< var group_name >}} Handbook"
  # cover-image: "cover.png"
  search: true
  repo-url: https://github.com/cct-datascience/group-handbook-template
  repo-actions: [edit, issue]
  author: 
    - name: Jim Jones
      orcid: 0000-0000-0000-0000
    - name: Student Scott
    - name: Staff Member Mary
  date: "11/28/2023"
  chapters:
    - index.qmd
    - contributing.qmd
    - href: code-of-conduct.qmd
      text: "Code of Conduct"
    - group-expectations.qmd
    - onboarding.qmd
    - offboarding.qmd
    - research-best-practices.qmd
    - authorship.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    link-external-icon: true
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: darkly

editor: 
  markdown:
    wrap: sentence
