project:
  type: book
execute: 
  freeze: auto
book:
  title: "GROUP_NAME Handbook"
  search: true
  repo-url: https://github.com/cct-datascience/group-handbook-template
  repo-actions: [edit, issue]
  author: 
    - name: PI_NAME
      orcid: 0000-0000-0000-0000
    #add all contributors as additional authors
  date: "11/28/2023"
  chapters:
    - index.qmd #the landing page *must* be called 'index.qmd'
    - contributing.qmd
    - href: code-of-conduct.qmd
      text: "Code of Conduct"
    - group-expectations.qmd
    - onboarding.qmd
    - offboarding.qmd
    - research-best-practices.qmd
    - authorship.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: darkly

editor: 
  markdown:
    wrap: sentence
